FEAT: USER Repository/data
dr-Ariawan-s-Project/api-drariawan pull request #38
Opened 2023-09-25 13:58 UTC by fauzilax

Maaf mas, kamil branch yang sebelumnya error pas di rebase jadi bikin branch baru

2023-09-26 22:38 UTC, rachmankamil requested changes

2023-09-26 22:38 UTC, rachmankamil commented on migration/20230819040447_create-table-user.up.sql
> +ALTER TABLE users RENAME COLUMN picture TO url_picture;
harusnya bikin file migration baru sih ini.

2023-09-26 22:38 UTC, rachmankamil commented on utils/encrypt/jwt.go
> +	// return userId
ini yang di comment di perlukan atau ndak ya?

2023-09-26 22:38 UTC, rachmankamil commented on features/users/service/logic.go
> +	log.Println(userID)
banyak banget print log ini, kalau mau pake log print, formatnya harus di samain ya. dan harus lebih jelas dengan format json juga.

2023-09-26 22:39 UTC, rachmankamil commented
@fauzilax aku ada beberapa masukan yaaa

2023-09-27 01:22 UTC, fauzilax commented on migration/20230819040447_create-table-user.up.sql
> +ALTER TABLE users RENAME COLUMN picture TO url_picture;
oh baik mas

2023-09-27 01:22 UTC, fauzilax commented on utils/encrypt/jwt.go
> +	// return userId
siap mas nanti direvisi

2023-09-27 01:23 UTC, fauzilax commented on features/users/service/logic.go
> +	log.Println(userID)
baik mas nanti saya perbaiki

2023-09-28 00:39 UTC, closed without merging