Schedulehandler
dr-Ariawan-s-Project/api-drariawan pull request #40
Opened 2023-09-26 15:25 UTC by fauzilax

2023-09-26 22:51 UTC, rachmankamil requested changes

2023-09-26 22:51 UTC, rachmankamil commented on app/router/router.go
> +	v1Schedule.POST("", sysRoute.scheduleHandler.Create())
ini schedule handler , tapi kok masukin user juga bro @fauzilax ?

2023-09-26 22:51 UTC, rachmankamil commented on features/schedule/data/query.go
> +		log.Println("query error", err.Error())
ini log println sama seperti yang tadi ya, better di sesuaikan menggunakan json object aja.

2023-09-26 22:51 UTC, rachmankamil commented on features/schedule/entity.go
> +
Handler Interface ndak boleh ada, jadinya di entity tidak clean. entity tidak boleh ada independent ke 3rd party.

2023-09-26 22:51 UTC, rachmankamil commented on features/users/data/query.go
> +		log.Println("query error", err.Error())
ini kenapa ada hardcoded gini?

2023-09-26 22:51 UTC, rachmankamil commented on features/users/data/query.go
> +		log.Println("query error", err.Error())
find username or email, tapi di where cuma username aja nih

2023-09-26 22:51 UTC, rachmankamil commented on features/users/entity.go
>  }
ini juga, harusnya ndak ada ya di handler.

2023-09-26 22:51 UTC, rachmankamil commented on features/users/service/logic.go
> +	userRepo users.UserData
dari sisi clean code ndak boleh ini seharusnya. `users.UserData` => `users.Data`

2023-09-26 22:51 UTC, rachmankamil commented on migration/20230819040447_create-table-user.up.sql
> +ALTER TABLE users RENAME COLUMN picture TO url_picture;
ini juga tadi udah di review deh, salah ambil brach kah?

2023-09-27 00:29 UTC, fauzilax commented on features/users/data/query.go
> +		log.Println("query error", err.Error())
Default nya mas, nanti diganti pas update user

2023-09-27 00:30 UTC, fauzilax commented on features/schedule/entity.go
> +
Siap mas

2023-09-27 00:35 UTC, fauzilax commented on app/router/router.go
> +	v1Schedule.POST("", sysRoute.scheduleHandler.Create())
Maaf mas sepertinya ada yang lupa saya masukin pas push di branch nya, jd masukin nya di branch schedule, 🙏

2023-09-27 00:35 UTC, fauzilax commented on features/schedule/data/query.go
> +		log.Println("query error", err.Error())
Baik mas

2023-09-27 00:39 UTC, fauzilax commented on features/users/data/query.go
> +		log.Println("query error", err.Error())
Maaf mas itu saya masih agak bingung seperti yang mas kamil jelaskan sebelumnya untuk keperluan login, jadi khusus yang itu belum saya kerjakan lagi

2023-09-27 00:39 UTC, fauzilax commented on features/users/service/logic.go
> +	userRepo users.UserData
Siap mas

2023-09-27 00:40 UTC, fauzilax commented on migration/20230819040447_create-table-user.up.sql
> +ALTER TABLE users RENAME COLUMN picture TO url_picture;
Saya buat branch baru jadi sekalian di perbaiki seperti yang disaranin sebelumnya, branch sebelumnya bermasalah pas rebase mas 🙏

2023-09-30 00:35 UTC, rachmankamil approved these changes

2023-09-30 00:37 UTC, merged