Userhandlerperbaikan
dr-Ariawan-s-Project/api-drariawan pull request #49
Opened 2023-09-28 01:41 UTC by fauzilax

Revisi untuk beberapa kesalahan sebelumnya
- mengganti nama interface method di entity yang sebelumnya UserService menjadi Service dan UserData menjadi Data
- menambahkan Field Request dan response baru "Phone"
- menghapus comment code yang tidak dipakai di folder encrypt->jwt

2023-09-30 23:14 UTC, rachmankamil requested changes

2023-09-30 23:14 UTC, rachmankamil commented on migration/20230928001719_create_alter_table_users.down.sql
> +DROP TABLE IF EXISTS `users`;
upnya pake alter table, tapi downnya kok drop table @fauzilax ? harusnya downnya juga alter table mengembalikan ke state sebelum di alter.

2023-09-30 23:14 UTC, rachmankamil commented
@fauzilax kemarin habis aku rebase ya, dan semua aku based on incoming aja. jadi harusnya perubahan kamu semua masih ada. 

@iffakhry tolong di review juga ya, soalnya habis aku rebase

2023-09-30 23:51 UTC, closed without merging

2023-10-01 00:26 UTC, fauzilax commented on migration/20230928001719_create_alter_table_users.down.sql
> +DROP TABLE IF EXISTS `users`;
siap mas kamil