CHORE: USER VALIDATION
dr-Ariawan-s-Project/api-drariawan pull request #61
Opened 2023-10-03 16:31 UTC by fauzilax

- untuk insert data hanya bisa dilakukan oleh role admin
- Validasi input insert data (
   name => 'required',
   email => 'email,required'
   phone => 'numeric,required',
   role => 'alphabet,required',
   password => 'alphanumeric,required'
   specialization => 'alphabet,required')
- validasi input update data
   name => 'alphabet',
   email => 'email'
   phone => 'numeric',
   role => 'alphabet',
   password => 'alphanumeric'
   specialization => 'alphabet')

2023-10-03 22:31 UTC, rachmankamil requested changes

2023-10-03 22:31 UTC, rachmankamil commented on app/router/router.go
>  	v1User.PUT("", sysRoute.userHandler.Update(), echojwt.WithConfig(echojwt.Config{SigningMethod: "HS256", SigningKey: []byte(config.InitConfig().JWT_SECRET)}))
ini middleware echojwt ga bisa di reuse aja kah?

2023-10-03 22:31 UTC, rachmankamil commented on features/users/service/logic.go
> +	if strings.ToLower(role) != "admin" {
`"admin"` di buat `const` ya. takutnya ada typo

2023-10-03 22:31 UTC, rachmankamil commented on features/users/service/logic.go
> +		return users.UsersCore{}, errors.New("invalid access")
error ini juga ada const klo ga salah ya kan di siapin sama @iffakhry

2023-10-03 22:31 UTC, rachmankamil commented on main.go
> +	e.Logger.Fatal(e.Start(":80"))
ini portnya kenapa di ganti? @iffakhry @fauzilax

2023-10-04 01:47 UTC, fauzilax commented on app/router/router.go
>  	v1User.PUT("", sysRoute.userHandler.Update(), echojwt.WithConfig(echojwt.Config{SigningMethod: "HS256", SigningKey: []byte(config.InitConfig().JWT_SECRET)}))
hmm nanti di perbaiki mas biar bisa reuse

2023-10-04 01:50 UTC, fauzilax commented on main.go
> +	e.Logger.Fatal(e.Start(":80"))
maaf mas kamil di saya gak bisa pake port :80, jadi kadang saat push lupa ganti mas

2023-10-04 13:10 UTC, closed without merging