CHORE: SCHEDULE VALIDATION
dr-Ariawan-s-Project/api-drariawan pull request #62
Opened 2023-10-03 19:41 UTC by fauzilax

Penambahan Validasi dan Response get all schedule

2023-10-03 22:35 UTC, rachmankamil requested changes

2023-10-03 22:35 UTC, rachmankamil commented on features/schedule/data/query.go
> +	}
- log apakah memang di perlukan di sini?
- error const sudah di sediakan oleh @iffakhry

2023-10-03 22:35 UTC, rachmankamil commented on features/schedule/data/query.go
> +	}
string error lebih baik masuk constanta ya.. jadi bisa di reuse.

2023-10-03 22:35 UTC, rachmankamil commented on features/schedule/data/query.go
> +
ini juga errornya sama.

2023-10-04 01:45 UTC, fauzilax commented on features/schedule/data/query.go
> +	}
oh maaf mas lupa dihapus, itu kemarin buat testing pengen liat hasil nya yang keluar yang mana, nanti segera diperbaiki

2023-10-04 01:46 UTC, fauzilax commented on features/schedule/data/query.go
> +	}
baik mas

2023-10-04 19:50 UTC, closed without merging