FEAT: add new features booking
dr-Ariawan-s-Project/api-drariawan pull request #63
Opened 2023-10-04 19:15 UTC by fauzilax

2023-10-05 10:11 UTC, iffakhry commented on app/router/router.go
> +	v1Booking.POST("/delete", sysRoute.bookingHandler.Delete())
ini kenapa gak pakai http method `DELETE` aja @fauzilax ?

2023-10-05 10:14 UTC, iffakhry commented
@fauzilax sepertinya kita juga perlu buat endpoint untuk melihat jadwal yang sudah terbooking based on dokter.
Jadi nanti dokter bisa lihat list pasient dan hari konsultasinya dengan dokternya.

2023-10-06 02:09 UTC, iffakhry requested changes

2023-10-06 02:09 UTC, iffakhry commented on features/booking/service/logic.go
> +}
@fauzilax zi, ini perlu divalidate lagi. check availability schedule dokter nya. dan check apakah pasien tsb sudah pernah konsultasi di seminggu terakhir. 
soalnya dari user story yang ada di whimsical itu ada validasi "only 1 reservation per week".
lalu nanti kalau ok, kirim email notifikasi ke pasien nya

2023-10-10 02:03 UTC, fauzilax commented on features/booking/service/logic.go
> +}
boleh mas fakhry nanti saya validasi

2023-10-14 11:46 UTC, closed without merging