Bookingbu
dr-Ariawan-s-Project/api-drariawan pull request #71
Opened 2023-10-14 11:52 UTC by fauzilax

2023-10-17 06:42 UTC, iffakhry requested changes

2023-10-17 06:42 UTC, iffakhry commented on features/booking/handler/handler.go
> +		mapResponse, httpCode := helpers.WebResponseSuccess("[success] read data", config.FEAT_USER_CODE, map[string]interface{}{"data": "string"})
tolong dicheck lagi zi, ini harusnya error code nya bukan user, tapi feature booking

2023-10-17 06:42 UTC, iffakhry commented on features/booking/handler/handler.go
> +		return c.JSON(httpCode, mapResponse)
ini juga error code nya diganti ya

2023-10-17 06:42 UTC, iffakhry commented on migration/20231003195654_create_table_booking.up.sql
> +);
zi, id better pakai varchar, soalnya ada kemungkinan akan ada banyak data disini. 
lalu kalau melihat desain yg dibuat FE, sepertinya perlu ditambahkan kode booking.

2023-10-17 07:09 UTC, fauzilax commented on features/booking/handler/handler.go
> +		mapResponse, httpCode := helpers.WebResponseSuccess("[success] read data", config.FEAT_USER_CODE, map[string]interface{}{"data": "string"})
siap mas malem saya perbaiki,

2023-10-20 02:53 UTC, iffakhry requested changes

2023-10-20 02:53 UTC, iffakhry commented on features/booking/entity.go
> +}
zi, di core ada json ini nanti untuk digunakan dibagian mana?

2023-10-20 02:53 UTC, iffakhry commented on features/booking/handler/handler.go
> +
zi, kalau kamu masukkan ke map seperti ini bukannya nanti di response jsonnya akan ada nested data ya?
```
{
"data":
    {
      "data: {
                .....
         }
      }
}
```

coba pakai pendkatan ini. 
atau bisa lihat di feature questioner
```
mapResponse, httpCode := helpers.WebResponseSuccess("[success] read data", config.FEAT_DASHBOARD_CODE, questionerDashboardRespose)
	return c.JSON(httpCode, mapResponse)
```

2023-10-20 02:56 UTC, fauzilax commented on features/booking/entity.go
> +}
itu response mas nantinya yang tampil

2023-10-20 02:56 UTC, fauzilax commented on features/booking/handler/handler.go
> +
ok mas fakhry

2023-10-20 02:58 UTC, iffakhry commented on features/booking/entity.go
> +}
gak pakai struct response sendiri?

2023-10-21 10:19 UTC, fauzilax commented on features/booking/entity.go
> +}
pengennya sih mas, tapi itu masih bisa dimanfaatkan, soalnya nganggur juga polosan, mending sekalian dipake buat response, 
tapi kalo misalnya mas fakhry minta pake response sendiry nanti saya tambahin mas fakhry

2023-10-23 16:41 UTC, iffakhry approved these changes

2023-10-24 22:38 UTC, merged